<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>2apl</string>
		<string>mas</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>keyEquivalent</key>
	<string>^~@</string>
	<key>name</key>
	<string>2APL</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(Beliefs|Goals|BeliefUpdates|Plans|PG-rules|PC-rules|PR-rules)\b</string>
			<key>name</key>
			<string>keyword.control.2APL</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(Include)\b:\s\w+\b(.2apl)\b</string>
			<key>name</key>
			<string>keyword.other.include.2APL</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(if|then|else|while|for|do)\b</string>
			<key>name</key>
			<string>keyword.control.conditionals.2APL</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true|not|false|null)\b</string>
			<key>name</key>
			<string>constant.language.2APL</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\{|\}</string>
			<key>name</key>
			<string>punctuation.section.scope.2APL</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\[|\]</string>
			<key>name</key>
			<string>punctuation.section.array.2APL</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\(|\)</string>
			<key>name</key>
			<string>punctuation.section.function.2APL</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(&lt;-)|&lt;|&gt;|\||&amp;|\+</string>
			<key>name</key>
			<string>keyword.operator.rule.2APL</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(and|or)\b</string>
			<key>name</key>
			<string>keyword.operator.logical.2APL</string>
		</dict>
		<dict>
			<key>match</key>
			<string>@\w+</string>
			<key>name</key>
			<string>entity.other.environment.2APL</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(send|B|G|adopta|adoptz|dropgoal|dropsubgoals|dropsupergoals)\b(?=\()</string>
			<key>name</key>
			<string>entity.name.function.builtin.2APL</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\w+(?=\()</string>
			<key>name</key>
			<string>entity.name.function.2APL</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Match all variables (starting with upper case).</string>
			<key>match</key>
			<string>(\b[A-Z]+\w*(?=\W))</string>
			<key>name</key>
			<string>variable.parameter.2APL</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\b[a-z]+\w*(?=\W))</string>
			<key>name</key>
			<string>constant.other.2APL</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.java</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(//).*$\n?</string>
			<key>name</key>
			<string>comment.line.double-slash.2APL</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.java</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(%).*$\n?</string>
			<key>name</key>
			<string>comment.line.percentage.2APL</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.APLList.begin.2APL</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>APLList</string>
			<key>end</key>
			<string>\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.APLList.end.2APL</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.structure.APLList.2APL</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>,</string>
					<key>name</key>
					<string>punctuation.separator.APLList.2APL</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.2APL</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.2APL</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.2APL</string>
	<key>uuid</key>
	<string>6CE0331B-5181-4FB3-B02E-D6E273354F2A</string>
</dict>
</plist>
